export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_SIGNUP_PENDING = 'USER_SIGNUP_PENDING';
export const USER_SIGNUP_FULFILLED = 'USER_SIGNUP_FULFILLED';
export const USER_SIGNUP_REJECTED = 'USER_SIGNUP_REJECTED';